version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercurio
    ports: ["5433:5432"]
  adminer:
    image: adminer:4
    ports: ["8080:8080"]
    depends_on: [postgres]
