name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mercurio
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mercurio
      JWT_SECRET: testsecret
      PORT: 4000
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: nohup npx tsx src/main.ts &
      - run: sleep 3 && curl -fsS http://localhost:4000/salud
      - run: pkill -f "tsx src/main.ts" || true
